language: java
sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
  email:
    recipients:
      - goncharov.vd@mail.ru
    on_success: never
    on_failure: always