version: '3.1'

services:
  database:
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: schedule_boot
    volumes:
      - pg:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  spring-boot-app:
    container_name: schedule-app
    build: ./
    depends_on:
      - database
    ports:
      - 8082:8080
volumes:
  pg: