spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/schedule_boot
    username: postgres
    password: root
    initialization-mode: always
    sql-script-encoding: UTF-8
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  thymeleaf: 
    cache: false
    encoding: UTF-8
  messages:
    encoding: UTF-8
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
app:
  title: 'DVFU SCHEDULE'