spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/schedule_boot?serverTimezone=UTC
    username: root
    password: mysql
    sql-script-encoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        temp.use_jdbc_metadata_defaults: false
  queries:
    users-query: 'select email, password, active from users where email=?'
    roles-query: 'select u.email, r.role from users u inner join user_role ur on (u.id=ur.user_id) inner join roles r on (ur.role_id=r.id) where u.email=?'
  thymeleaf: 
    cache: false
    encoding: UTF-8
  messages:
    encoding: UTF-8
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    org:
      hibernate:
        SQL: debug
app:
  title: 'DVFU SCHEDULE'